#!/bin/bash
mvn clean package
java --module-path javafx-sdk-11Mac/lib --add-modules javafx.controls,javafx.media -cp .:json-simple-1.1.1.jar:jimObjModelImporterJFX.jar:target/aquavias-game-0.0.1-SNAPSHOT.jar Main
